export {
  buildIndex,
  buildSerializedIndex,
  defineFields,
  loadIndex,
  type DocumentSearchOptions,
  type LoadSearchIndexOptions,
  type SearchField,
  type SearchIndex,
  type SearchPrimitive,
  type SearchQuery,
  type SearchResult,
  type SearchValue,
  type SerializedSearchIndex,
  type SynonymMap,
  type SynonymResolver,
  type SynonymSource,
  type TextAnalyzer,
  type TypoToleranceOptions,
} from "./document-search";
